### ISSUE TITLE
Is there a tutorial for how you created your site?

### ISSUE THREAD

**Issue by technoplato** [iboB/ibob.github.com#3]

**Comment by technoplato** [comment]
Also, I greatly enjoyed your writing and demeanor in your c++ as first language article. Thank you for sharing that with us.

**Comment by iboB** [comment]
Hi. The website uses [Jekyll](https://jekyllrb.com/) and [GitHub pages](https://pages.github.com/). 

I use this one for experiments and I made the template from scratch (which is not a good idea if all you want is a personal website). You can get started with your own site in minutes if you start from here: https://github.com/barryclark/jekyll-now

There are many other examples and tutorials if you start from here: https://github.com/planetjekyll/awesome-jekyll
